# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23fcab1fccdb182676cc9cceebe5c22031f80908d95b309cc7e7afba2c18135468d082a9e996d0c8cf7f8614afcd1717f4fb2e094cf44f87770ca780a213f631

test:
  secret_key_base: 8b8514fc9325e59cba879cf1808930d53fc3088281d824fa9e21623e9eedbf0a2f7bee82e083134d84847ee0cf0fc0ec91d92437eca9a192c95ecfcd4fba3ec1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
